### PR TITLE
Fill borders

### PR DESCRIPTION
**Pull request by akaihola**
Stretch the edges of the remaining "brightest" or "darkest" map so the image has again the same size as the original.

Based on #4.

### CODE REVIEW

**Comment by akaihola** [comment]
@Sorseg wanna join us? We're having fun and learning Rust here together.

**Comment by Sorseg** [comment]
@akaihola This is Filipp, this is my old account 😄

**Comment by akaihola** [comment]
@Sorseg, whaat, you did gvanrossum/gvanrossum.github.io#1!

**Comment by samoylovfp** [comment]
Yay these three characters went to the Arctic vault!

**Comment by samoylovfp** [comment]
This looks great, though the function signatures are a little scary but I guess there is little we can do here

**Review by samoylovfp — APPROVED** [review]

**Comment by akaihola** [comment]
Oh @samoylovfp by all means I'd really enjoy it if you can figure out a way to simplify the signatures!

**Pull request merged**
